package model.views;

import java.awt.Color;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.controllers.UniversalController;
import model.repositories.dao.impl.MacAdressDAO;
import model.repositories.dao.impl.OrderListDAO;
import model.entities.MacAdress;
import model.entities.OrderList;

public class CarrinhoView extends javax.swing.JFrame {

    /**
     * Creates new form Fr_Carrinho
     */
    public CarrinhoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_remover = new javax.swing.JButton();
        cb_Pedidos = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_pedidosPreco = new javax.swing.JTextArea();
        lb_total = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_pedidosNome = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_pedidosId = new javax.swing.JTextArea();
        bt_concluir = new javax.swing.JButton();
        bt_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carrinho");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bt_remover.setBackground(java.awt.Color.lightGray);
        bt_remover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_remover.setText("Remover do carrinho");
        bt_remover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_removerMouseMoved(evt);
            }
        });
        bt_remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_removerMouseExited(evt);
            }
        });
        bt_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerActionPerformed(evt);
            }
        });

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ta_pedidosPreco.setBackground(new java.awt.Color(240, 240, 240));
        ta_pedidosPreco.setColumns(20);
        ta_pedidosPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ta_pedidosPreco.setRows(5);
        ta_pedidosPreco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ta_pedidosPreco.setEnabled(false);
        ta_pedidosPreco.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane4.setViewportView(ta_pedidosPreco);

        lb_total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_total.setBorder(javax.swing.BorderFactory.createTitledBorder("TOTAL"));
        lb_total.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_total.setOpaque(true);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ta_pedidosNome.setBackground(new java.awt.Color(240, 240, 240));
        ta_pedidosNome.setColumns(20);
        ta_pedidosNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ta_pedidosNome.setRows(5);
        ta_pedidosNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ta_pedidosNome.setEnabled(false);
        ta_pedidosNome.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(ta_pedidosNome);

        jLabel1.setBackground(new java.awt.Color(220, 220, 220));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("        ID                                DESCRIÇÃO                       PREÇO  ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(61, 227));

        ta_pedidosId.setBackground(new java.awt.Color(240, 240, 240));
        ta_pedidosId.setColumns(20);
        ta_pedidosId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ta_pedidosId.setRows(5);
        ta_pedidosId.setTabSize(10);
        ta_pedidosId.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ta_pedidosId.setEnabled(false);
        ta_pedidosId.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane3.setViewportView(ta_pedidosId);

        bt_concluir.setBackground(java.awt.Color.lightGray);
        bt_concluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_concluir.setText("Concluir compra");
        bt_concluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_concluirMouseMoved(evt);
            }
        });
        bt_concluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_concluirMouseExited(evt);
            }
        });
        bt_concluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_concluirActionPerformed(evt);
            }
        });

        bt_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return-lightgray-32x32.jpg"))); // NOI18N
        bt_return.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_return.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_returnMouseMoved(evt);
            }
        });
        bt_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_returnMouseExited(evt);
            }
        });
        bt_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bt_concluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_remover))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(bt_concluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(bt_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(bt_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerActionPerformed

        OrderListDAO requestListDaOJDBC = new OrderListDAO();

        String iten = (String) cb_Pedidos.getSelectedItem();
        String msg = requestListDaOJDBC.deleteByUsername_carrinho(iten);

        JOptionPane.showMessageDialog(null, msg, "WARNING", JOptionPane.WARNING_MESSAGE);
        this.dispose();
        this.setVisible(true);

    }//GEN-LAST:event_bt_removerActionPerformed

    private void bt_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_returnActionPerformed
        TelaPrincipalView telaPrincipal = new TelaPrincipalView();
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_bt_returnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refresh();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        try {
            Thread.sleep(500);
            refresh();
        } catch (InterruptedException ex) {
            Logger.getLogger(CarrinhoView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowActivated

    private void bt_returnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_returnMouseMoved
        bt_return.setBackground(Color.GREEN);
    }//GEN-LAST:event_bt_returnMouseMoved

    private void bt_returnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_returnMouseExited
        bt_return.setBackground(Color.lightGray);
    }//GEN-LAST:event_bt_returnMouseExited

    private void bt_concluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_concluirActionPerformed

        MacAdress macAdress = new MacAdress();
        MacAdressDAO macAdressDAO = new MacAdressDAO();
        OrderListDAO requestListDAO = new OrderListDAO();
        TelaPrincipalView telaPrincipal = new TelaPrincipalView();

        String iten = (String) cb_Pedidos.getSelectedItem();
        String msg = requestListDAO.updateByUsername_carrinho(iten, macAdressDAO.findByUsername(macAdress));

        JOptionPane.showMessageDialog(null, msg, "WARNING", JOptionPane.WARNING_MESSAGE);

        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_concluirActionPerformed

    private void bt_removerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_removerMouseExited
        new UniversalController().btMouseExited(bt_remover);
    }//GEN-LAST:event_bt_removerMouseExited

    private void bt_removerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_removerMouseMoved
        new UniversalController().btMouseMoved(bt_remover);
    }//GEN-LAST:event_bt_removerMouseMoved

    private void bt_concluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_concluirMouseExited
        new UniversalController().btMouseExited(bt_concluir);
    }//GEN-LAST:event_bt_concluirMouseExited

    private void bt_concluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_concluirMouseMoved
        if (lb_total.getText().equals("R$ 0,00")) {
            new UniversalController().btNoFunction(bt_concluir);
        } else {
            new UniversalController().btMouseMoved(bt_concluir);
        }
    }//GEN-LAST:event_bt_concluirMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarrinhoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_concluir;
    private javax.swing.JButton bt_remover;
    private javax.swing.JButton bt_return;
    private javax.swing.JComboBox<String> cb_Pedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lb_total;
    private javax.swing.JTextArea ta_pedidosId;
    private javax.swing.JTextArea ta_pedidosNome;
    private javax.swing.JTextArea ta_pedidosPreco;
    // End of variables declaration//GEN-END:variables

    public void refresh() {
        MacAdress macAdress = new MacAdress();
        MacAdressDAO macAdressDAO = new MacAdressDAO();
        OrderListDAO requestListDAO = new OrderListDAO();
        List<OrderList> list = new ArrayList<>();

        list = requestListDAO.findByUsername_carrinho(macAdressDAO.findByUsername(macAdress));

        String textId = "";
        String textNome = "";
        String textPreco = "";
        double total = 0;

        if (list != null) {

            String[] text = new String[list.size()];
            int n = 0;
            for (OrderList lista : list) {
                textId += lista.getId() + "\n\n";
                textNome += lista.getName() + "\n\n";
                textPreco += String.format("R$ %.2f \n\n", lista.getPrice());
                total += lista.getPrice();

                text[n] = lista.getName();
                n++;
            }

            ta_pedidosId.setText(textId);
            ta_pedidosNome.setText(textNome);
            ta_pedidosPreco.setText(textPreco);
            lb_total.setText(String.format("R$ %.2f", total));

            cb_Pedidos.setModel(new javax.swing.DefaultComboBoxModel<>(text));
        } else {

            String[] text = new String[1];
            text[0] = "Lista vazia!";

            ta_pedidosId.setText(null);
            ta_pedidosNome.setText(null);
            ta_pedidosPreco.setText(null);
            cb_Pedidos.setModel(new javax.swing.DefaultComboBoxModel<>(text));
            lb_total.setText("R$ 0,00");
        }
    }

}
