package model.views;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.controllers.UniversalController;

public class ConfigsView extends javax.swing.JFrame {

    public ConfigsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_return = new javax.swing.JButton();
        bt_carrinho = new javax.swing.JButton();
        bt_formsPag = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        bt_pedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");
        setResizable(false);

        bt_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return-lightgray-32x32.jpg"))); // NOI18N
        bt_return.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_return.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_returnMouseMoved(evt);
            }
        });
        bt_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_returnMouseExited(evt);
            }
        });
        bt_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_returnActionPerformed(evt);
            }
        });

        bt_carrinho.setBackground(java.awt.Color.lightGray);
        bt_carrinho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_carrinho.setText("Carrinho de Compras");
        bt_carrinho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_carrinhoMouseMoved(evt);
            }
        });
        bt_carrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_carrinhoMouseExited(evt);
            }
        });
        bt_carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_carrinhoActionPerformed(evt);
            }
        });

        bt_formsPag.setBackground(java.awt.Color.lightGray);
        bt_formsPag.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_formsPag.setText("Formas de Pagamento");
        bt_formsPag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_formsPagMouseMoved(evt);
            }
        });
        bt_formsPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_formsPagMouseExited(evt);
            }
        });
        bt_formsPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_formsPagActionPerformed(evt);
            }
        });

        bt_edit.setBackground(java.awt.Color.lightGray);
        bt_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_edit.setText("Editar Perfil");
        bt_edit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_editMouseMoved(evt);
            }
        });
        bt_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_editMouseExited(evt);
            }
        });
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_pedidos.setBackground(java.awt.Color.lightGray);
        bt_pedidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_pedidos.setText("Histórico de Pedidos");
        bt_pedidos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_pedidosMouseMoved(evt);
            }
        });
        bt_pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_pedidosMouseExited(evt);
            }
        });
        bt_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_carrinho)
                    .addComponent(bt_edit)
                    .addComponent(bt_formsPag)
                    .addComponent(bt_pedidos)
                    .addComponent(bt_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(bt_carrinho)
                .addGap(11, 11, 11)
                .addComponent(bt_edit)
                .addGap(11, 11, 11)
                .addComponent(bt_formsPag)
                .addGap(11, 11, 11)
                .addComponent(bt_pedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(bt_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_returnActionPerformed
        new UniversalController().onOffFrame(new TelaPrincipalView(), this);        
    }//GEN-LAST:event_bt_returnActionPerformed

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        JOptionPane.showMessageDialog(null, "Frame em Desenvolvimento", "WARNING", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_bt_editActionPerformed

    private void bt_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pedidosActionPerformed
        new UniversalController().onOffFrame(new HistoricoPedidosView(), this);        
    }//GEN-LAST:event_bt_pedidosActionPerformed

    private void bt_pedidosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pedidosMouseMoved
        bt_pedidos.setBackground(Color.GREEN);
    }//GEN-LAST:event_bt_pedidosMouseMoved

    private void bt_pedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pedidosMouseExited
        bt_pedidos.setBackground(Color.lightGray);
    }//GEN-LAST:event_bt_pedidosMouseExited

    private void bt_formsPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_formsPagActionPerformed
       JOptionPane.showMessageDialog(null, "Frame em Desenvolvimento", "WARNING", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_bt_formsPagActionPerformed

    private void bt_carrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_carrinhoActionPerformed
        new UniversalController().onOffFrame(new CarrinhoView(), this);        
    }//GEN-LAST:event_bt_carrinhoActionPerformed

    private void bt_returnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_returnMouseMoved
        bt_return.setBackground(Color.GREEN);
    }//GEN-LAST:event_bt_returnMouseMoved

    private void bt_returnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_returnMouseExited
        bt_return.setBackground(Color.lightGray);
    }//GEN-LAST:event_bt_returnMouseExited

    private void bt_carrinhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_carrinhoMouseExited
        bt_carrinho.setBackground(Color.lightGray);
    }//GEN-LAST:event_bt_carrinhoMouseExited

    private void bt_carrinhoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_carrinhoMouseMoved
        bt_carrinho.setBackground(Color.GREEN);
    }//GEN-LAST:event_bt_carrinhoMouseMoved

    private void bt_formsPagMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_formsPagMouseExited
        new UniversalController().btMouseExited(bt_formsPag);
    }//GEN-LAST:event_bt_formsPagMouseExited

    private void bt_formsPagMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_formsPagMouseMoved
        new UniversalController().btNoFunction(bt_formsPag);
    }//GEN-LAST:event_bt_formsPagMouseMoved

    private void bt_editMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_editMouseMoved
        new UniversalController().btNoFunction(bt_edit);
    }//GEN-LAST:event_bt_editMouseMoved

    private void bt_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_editMouseExited
        new UniversalController().btMouseExited(bt_edit);
    }//GEN-LAST:event_bt_editMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_carrinho;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_formsPag;
    private javax.swing.JButton bt_pedidos;
    private javax.swing.JButton bt_return;
    // End of variables declaration//GEN-END:variables
}
